import { useCallback, useEffect, useState } from "react";
import { ConversationThread, type ConversationMessage } from "../components/ConversationThread";
import { EscalationCard, type EscalationSummary } from "../components/EscalationCard";
import { logInboxEvent } from "../lib/analytics";
import { supabase } from "../lib/supabase";

export default function StaffInbox() {
  const [property, setProperty] = useState<{ id: string; name: string } | null>(null); const [items, setItems] = useState<EscalationSummary[]>([]); const [selectedId, setSelectedId] = useState(() => new URLSearchParams(location.search).get("escalation")); const [messages, setMessages] = useState<ConversationMessage[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const fetchItems = useCallback(async (propertyId: string) => { const { data, error: queryError } = await supabase.from("escalations").select("id,status,reason,created_at,conversations(id,channel,guest_name,thread_key)").eq("property_id", propertyId).in("status", ["new", "in_progress"]).order("created_at", { ascending: false }); if (queryError) setError("Escalations could not be loaded. Try refreshing the page."); else { const summaries = (data ?? []) as unknown as EscalationSummary[]; const enriched = await Promise.all(summaries.map(async (item) => { const { data: latest } = await supabase.from("messages").select("content").eq("conversation_id", item.conversations.id).eq("role", "user").order("created_at", { ascending: false }).limit(1).maybeSingle(); return { ...item, lastMessage: latest?.content }; })); setItems(enriched); setSelectedId((current) => current && enriched.some((item) => item.id === current) ? current : enriched[0]?.id ?? null); } setLoading(false); }, []);
  useEffect(() => { void (async () => { const { data: profile } = await supabase.from("user_profiles").select("property_id,properties(id,name)").maybeSingle(); let resolved = profile?.properties as unknown as { id: string; name: string } | null; if (!resolved) { const { data: owned } = await supabase.from("properties").select("id,name").limit(1).maybeSingle(); resolved = owned; } if (!resolved) { setError("Your account is not assigned to a property. Ask an administrator for access."); setLoading(false); return; } setProperty(resolved); await fetchItems(resolved.id); void logInboxEvent(resolved.id, "inbox_viewed"); })(); }, [fetchItems]);
  useEffect(() => { if (!property) return; const channel = supabase.channel(`escalations-${property.id}`).on("postgres_changes", { event: "*", schema: "public", table: "escalations", filter: `property_id=eq.${property.id}` }, () => void fetchItems(property.id)).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [property, fetchItems]);
  const selected = items.find((item) => item.id === selectedId) ?? null;
  useEffect(() => { if (!selected) { setMessages([]); return; } const url = new URL(location.href); url.searchParams.set("escalation", selected.id); history.replaceState(null, "", url); void (async () => { const { data } = await supabase.from("messages").select("id,role,content,created_at").eq("conversation_id", selected.conversations.id).order("created_at"); setMessages((data ?? []) as ConversationMessage[]); if (selected.status === "new") { await supabase.from("escalations").update({ status: "in_progress", opened_at: new Date().toISOString() }).eq("id", selected.id); if (property) void logInboxEvent(property.id, "escalation_opened", selected.id); } })(); const channel = supabase.channel(`messages-${selected.conversations.id}`).on("postgres_changes", { event: "INSERT", schema: "public", table: "messages", filter: `conversation_id=eq.${selected.conversations.id}` }, () => { void supabase.from("messages").select("id,role,content,created_at").eq("conversation_id", selected.conversations.id).order("created_at").then(({ data }) => setMessages((data ?? []) as ConversationMessage[])); }).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [selected?.id, property?.id]);
  async function updateStatus(status: "resolved", reassign = false) { if (!selected || !property) return; const { error: mutationError } = await supabase.from("escalations").update({ status, resolved_at: new Date().toISOString() }).eq("id", selected.id); if (mutationError) { setError("The escalation could not be updated. Try again."); void logInboxEvent(property.id, "escalation_update_error", selected.id); return; } void logInboxEvent(property.id, reassign ? "escalation_reassigned_to_ai" : "escalation_resolved", selected.id); await fetchItems(property.id); }
  async function send(message: string) { if (!selected || !property) return; void logInboxEvent(property.id, "staff_reply_started", selected.id); const { data, error: replyError } = await supabase.functions.invoke("staff-reply", { body: { escalation_id: selected.id, message } }); if (replyError || data?.error) { void logInboxEvent(property.id, "staff_reply_error", selected.id, { message: data?.error ?? replyError?.message }); throw new Error(data?.error ?? "Your reply could not be sent. Try again."); } void logInboxEvent(property.id, "staff_reply_sent", selected.id, { channel: selected.conversations.channel }); }
  return <main className="staff-inbox-shell"><header className="staff-inbox-header"><div><p className="eyebrow">Porter staff inbox</p><h1>{property?.name ?? "Guest escalations"}</h1></div><button className="text-button" onClick={() => void supabase.auth.signOut().then(() => location.assign("/staff/login"))}>Sign out</button></header>{error && <p className="error-text staff-inbox-error" role="alert">{error}</p>}<div className="staff-inbox-layout"><aside className="escalation-list" aria-labelledby="active-escalations-title"><h2 id="active-escalations-title">Active escalations</h2>{loading ? <p aria-live="polite">Loading escalations…</p> : items.length === 0 ? <p className="empty-inbox" aria-live="polite">No active escalations. You’re all caught up.</p> : <ul>{items.map((item) => <EscalationCard key={item.id} escalation={item} selected={item.id === selectedId} onSelect={() => setSelectedId(item.id)} />)}</ul>}</aside>{selected ? <ConversationThread escalation={selected} messages={messages} loading={loading} onSend={send} onResolve={() => updateStatus("resolved")} onReassign={() => updateStatus("resolved", true)} /> : <section className="conversation-empty"><h2>Select an escalation</h2><p>The full guest conversation will appear here.</p></section>}</div></main>;
}
